add url to the list-view
Roland-Hufnagel/capstone-project pull request #16
Opened 2022-10-24 13:33 UTC by Roland-Hufnagel

2022-10-24 13:35 UTC, Roland-Hufnagel commented
to have a look at it use:
https://capstone-project-git-feature-link-to-the-survey-roland-hufnagel.vercel.app/surveys

2022-10-24 13:54 UTC, ThomasF85 requested changes
Looks good. Just some minor changes requested.

2022-10-24 13:54 UTC, ThomasF85 commented on components/SurveyCard.js
> +        <button
This button has no accessible label.

2022-10-24 13:54 UTC, ThomasF85 commented on components/SurveyCard.js
> +const ButtonContainer = styled.section``;
There is no need for a styled component that does not do anything.

2022-10-24 13:54 UTC, ThomasF85 commented on components/SurveyCard.js
> +  gap: 10px;
You are using em and px here for things that should probably scale proportionally. Better don't mix them in that case.

2022-10-24 17:44 UTC, Roland-Hufnagel commented on components/SurveyCard.js
> +const ButtonContainer = styled.section``;
now i gave it the styles for its children.

2022-10-24 17:49 UTC, Roland-Hufnagel commented on components/SurveyCard.js
> +  gap: 10px;
Thats right. Thanks a lot.

2022-10-25 09:50 UTC, ThomasF85 approved these changes
Looks good!

2022-10-25 12:21 UTC, merged